using UnityEngine;

public class FloatingObject : MonoBehaviour
{
    public float amplitude = 0.5f; // Amplitud de la oscilaci贸n
    public float frequency = 1f; // Frecuencia de la oscilaci贸n

    private Vector3 initialPosition;

    private void Start()
    {
        initialPosition = transform.position;
    }

    private void Update()
    {
        // Calcular la posici贸n vertical oscilante
        Vector3 newPosition = initialPosition + Vector3.up * Mathf.Sin(Time.time * frequency) * amplitude;

        // Aplicar la nueva posici贸n al GameObject de texto
        transform.position = newPosition;
    }
}
